# Generated by Django 2.2 on 2019-04-15 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0013_servicetask_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartridge',
            name='comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='commentary'),
        ),
        migrations.AddField(
            model_name='printer',
            name='comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='commentary'),
        ),
        migrations.AddField(
            model_name='task',
            name='comment',
            field=models.CharField(blank=True, max_length=200, verbose_name='commentary'),
        ),
        migrations.AlterField(
            model_name='servicetask',
            name='comment',
            field=models.CharField(blank=True, default=' ', max_length=150, verbose_name='коментарий'),
        ),
        migrations.CreateModel(
            name='DetailsClient',
            fields=[
                ('inn', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='INN')),
                ('nickname', models.CharField(max_length=50, verbose_name='Псевдоним')),
                ('name', models.CharField(max_length=50, verbose_name='Юридическое название')),
                ('kpp', models.IntegerField(verbose_name='КПП')),
                ('adress', models.CharField(max_length=200, verbose_name='Юр.адрес')),
                ('rs', models.BigIntegerField(verbose_name='РС')),
                ('ks', models.BigIntegerField(verbose_name='КС')),
                ('bik', models.BigIntegerField(verbose_name='БИК')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='commentary')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.Client')),
            ],
        ),
    ]
