# Generated by Django 2.2 on 2019-04-15 15:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0014_auto_20190415_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('text', models.CharField(max_length=400, verbose_name='Сообщение')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('done', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistic.Employee')),
            ],
        ),
    ]
