# Generated by Django 2.2 on 2019-07-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0017_auto_20190428_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='get_set',
            field=models.CharField(choices=[('Забрать', 'Забрать'), ('Отдать', 'Отдать'), ('Самовывоз', 'Самовывоз')], default='Самовывоз', max_length=7, verbose_name='Отдать\\забрать'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='process',
            field=models.CharField(choices=[('Сделано', 'Выполнено'), ('Не сделано', 'Не выполнено')], default='Не сделано', max_length=15, verbose_name='Статус исполнения'),
        ),
    ]
