# Generated by Django 2.2 on 2019-07-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0019_usermessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=300, verbose_name='Адрес'),
        ),
    ]
