# Generated by Django 2.2 on 2019-07-14 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0020_auto_20190714_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistic.Employee', verbose_name='Исполнитель'),
        ),
    ]
