# Generated by Django 2.2 on 2019-07-14 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0021_auto_20190714_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistic.Client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='task',
            name='replace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistic.Cartridge', verbose_name='Подменка'),
        ),
    ]
