# Generated by Django 2.2 on 2019-07-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0022_auto_20190714_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=300, verbose_name='Что купить')),
                ('urls', models.CharField(default='', max_length=300, verbose_name='Где купить')),
                ('priority', models.CharField(choices=[('Не срочно', 'Не срочно'), ('Средняя', 'Средняя'), ('Срочно', 'Срочно')], default='Средняя', max_length=10, verbose_name='Срочность')),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='comment',
            field=models.CharField(blank=True, max_length=200, verbose_name='Коментарий'),
        ),
        migrations.AlterField(
            model_name='task',
            name='payment_method',
            field=models.CharField(choices=[('Нал', 'Нал'), ('Безнал', 'Безнал'), ('Без оплаты', 'Без оплаты')], default='Без оплаты', max_length=11, verbose_name='Нал\\Безнал'),
        ),
    ]
