# Generated by Django 2.2 on 2019-07-14 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0023_auto_20190714_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='urls',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Где купить'),
        ),
    ]
