# Generated by Django 2.2 on 2019-07-14 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0024_auto_20190714_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=300, verbose_name='Отзыв:')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
            ],
        ),
    ]
