# Generated by Django 2.2 on 2019-07-16 18:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0026_auto_20190716_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridge',
            name='code_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Кодовое название'),
        ),
        migrations.AlterField(
            model_name='cartridge',
            name='color',
            field=models.CharField(blank=True, choices=[('CYAN', 'cyan'), ('MAGENTA', 'magenta'), ('YELLOW', 'yellow'), ('BLACK', 'black')], max_length=10, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='cartridge',
            name='part',
            field=models.CharField(blank=True, choices=[('CART', 'картридж'), ('DRUM', 'драм'), ('TONER', 'туба')], max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='cartridge',
            name='price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='cartridge',
            name='resourse',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='adress',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='client',
            name='commentary',
            field=models.CharField(blank=True, max_length=300, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название или имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=300, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='firstname',
            field=models.CharField(blank=True, max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lastname',
            field=models.CharField(blank=True, max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middlename',
            field=models.CharField(blank=True, max_length=20, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='compatibility',
            field=models.ManyToManyField(blank=True, to='logistic.Cartridge'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='task',
            name='cashsumm',
            field=models.IntegerField(blank=True, help_text='Сумма денег которую надо получить от клиента, если оплата не по безналу', verbose_name='Сумма денег'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='task',
            name='employee',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='logistic.Employee', verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='task',
            name='get_set',
            field=models.CharField(blank=True, choices=[('Забрать', 'Забрать'), ('Отдать', 'Отдать'), ('Самовывоз', 'Самовывоз')], default='Самовывоз', max_length=7, verbose_name='Отдать\\забрать'),
        ),
        migrations.AlterField(
            model_name='task',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Нал', 'Нал'), ('Безнал', 'Безнал'), ('Без оплаты', 'Без оплаты')], default='Без оплаты', max_length=11, verbose_name='Нал\\Безнал'),
        ),
        migrations.AlterField(
            model_name='task',
            name='process',
            field=models.CharField(blank=True, choices=[('Сделано', 'Выполнено'), ('Не сделано', 'Не выполнено')], default='Не сделано', max_length=15, verbose_name='Статус исполнения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='replace',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='logistic.Cartridge', verbose_name='Подменка'),
        ),
        migrations.AlterField(
            model_name='task',
            name='working_time_1',
            field=models.CharField(blank=True, help_text='Со скольки', max_length=15, verbose_name='Рабочее время. С:'),
        ),
        migrations.AlterField(
            model_name='task',
            name='working_time_2',
            field=models.CharField(blank=True, help_text='До скольки', max_length=15, verbose_name='Рабочее время. ДО:'),
        ),
    ]
