# Generated by Django 2.2 on 2019-07-16 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0028_auto_20190716_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailsclient',
            name='client',
        ),
        migrations.AddField(
            model_name='client',
            name='detailsclient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='logistic.DetailsClient'),
        ),
        migrations.AlterField(
            model_name='task',
            name='employee',
            field=models.ForeignKey(blank=True, default=6, on_delete=django.db.models.deletion.PROTECT, to='logistic.Employee', verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='task',
            name='replace',
            field=models.ForeignKey(blank=True, default=7, on_delete=django.db.models.deletion.PROTECT, to='logistic.Cartridge', verbose_name='Подменка'),
        ),
    ]
