# Generated by Django 2.2 on 2019-07-16 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0029_auto_20190716_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='detailsclient',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='logistic.DetailsClient'),
        ),
    ]
