# Generated by Django 2.2 on 2019-07-16 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0030_auto_20190716_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='detailsclient',
        ),
    ]
