# Generated by Django 2.2 on 2019-07-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0031_remove_client_detailsclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsclient',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detailsclient',
            name='inn',
            field=models.BigIntegerField(unique=True, verbose_name='INN'),
        ),
    ]
