# Generated by Django 2.2 on 2019-07-16 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0032_auto_20190716_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='detailsclient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='logistic.DetailsClient'),
        ),
    ]
