# Generated by Django 2.2 on 2019-07-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0033_client_detailsclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='get_set',
            field=models.CharField(blank=True, choices=[('Забрать', 'Забрать'), ('Отдать', 'Отдать'), ('Самовывоз', 'Самовывоз')], default='Самовывоз', max_length=9, verbose_name='Отдать\\забрать'),
        ),
    ]
