# Generated by Django 2.2.4 on 2019-08-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0035_auto_20190716_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.CharField(max_length=300),
        ),
    ]
